[package]
name = "amo"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-sdk-dynamodb = "1.43.0"

aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
aws-types = "1.3.3"
tokio = { version = "1", features = ["full"] }